In [41]:
import numpy as np
import streamlit as st
import ipywidgets as widgets
from ipywidgets import VBox, HBox, Layout
from IPython.display import display, clear_output, Math
from math import ceil

In [42]:
def format_coef(prevcoef, coef, var):

    #Properly formats system of equations depending on coefficient

    if var == 'x':
        if coef == 0:
            return "&"
        elif coef == 1:
            return f'&{var}'
        elif coef == -1:
            return f"-&{var}"
        else:
            return f"{coef}&{var}"

    if coef == 0:
        return ""
    elif coef == 1 and prevcoef == 0:
        return f"{var}"
    elif coef == 1:
        return f"+{var}"
    elif coef == -1:
        return f"-{var}"
    elif coef > 0 and prevcoef != 0:
        return f"+{coef}{var}"
    else:
        return f"{coef}{var}"

def matrix_to_tex(matrix):
    
    # Converts matrix to system of equations
    a, b, c = matrix[0]
    d, e, f = matrix[1]

    # Builds LaTeX string
    latex_str = r"\begin{cases}"
    latex_str += r"\begin{aligned}"
    latex_str += f"{format_coef(1, a,'x')}{format_coef(a, b,'y')} = {c} \\\\"
    latex_str += f"{format_coef(1, d,'x')}{format_coef(d, e,'y')} = {f}"
    latex_str += r"\end{aligned}"
    latex_str += r"\end{cases}"

    return latex_str

def problem_generator(prob_num = 6, difficulty = "small", low = -12, high = 12):

    problems = []

    for _ in range(prob_num):
        if difficulty == "small":
            M = small_nice_2x3(low, high)
        else:
            M = big_nice_2x3(low, high)
        
        # Convert to LaTeX but return string instead of displaying
        latex = matrix_to_tex(M)
        problems.append(latex)

    return problems

def worksheet_generator(problems):

    header = r"""\documentclass[12pt]{article}
    \usepackage{amsmath}
    \begin{document}
    \section*{Row Reduction Practice Worksheet}
    """
    body = ""
    for i, p in enumerate(problems, start=1):
        body += f"Problem {i}: \\\\ {p} \\\\[1em]\n"
    
    footer = r"\end{document}"
    
    return header + body + footer


def big_nice_2x3(low, high):

    # Generates a (uniformly) random matrix

    while True:

        matrix = np.random.randint(low, high+1, size=(2,3))
        det = matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]

        if det != 0:
            break



    # Ensures the final matrix has a nice RREF

    b1 = matrix[0][2]
    b2 = matrix[1][2]

    matrix[0][2] = det*b1
    matrix[1][2] = det*b2

    return matrix

def small_nice_2x3(low, high):

    # Generates a (uniformly) random matrix

    while True: 

        matrix = np.random.randint(low, high+1, size=(2,3))

        # Checking for small determinant

        det = matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]

        if np.abs(det) <= 5 and det != 0:

            break

    # Ensures the final matrix has a nice RREF
    
    b1 = matrix[0][2]
    b2 = matrix[1][2]

    matrix[0][2] = det*b1
    matrix[1][2] = det*b2

    return matrix

#display(Math(matrix_to_tex(small_nice_2x3(-10,10))))


#def nice_matrix(m,n):



In [43]:
difficulty = st.selectbox(
    "Mode:",
    ["Small determinant", "Large determinant"]
)

generate = st.button("Generate system")

2026-01-19 15:02:12.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-19 15:02:12.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bar

In [44]:
def show_problems_in_columns(problems):
    # Start LaTeX string
    latex_str = r"\LARGE\displaystyle \begin{array}{c c}"  # two centered columns
    
    for i in range(0, len(problems), 2):
        row = problems[i:i+2]
        # Each problem goes in a cell; leave blank if only one problem in row
        if len(row) == 1:
            row_str = f"\\text{{{i+1}.)}} {row[0]} & ~ "
        else:
            row_str = f"\\text{{{i+1}.)}} {row[0]} & \\text{{{i+2}.)}} {row[1]}"
        latex_str += row_str + r" \\[50pt]"  # vertical spacing between rows

    latex_str += r"\end{array}"
    
    st.latex(latex_str)

if generate:
    prob_num = 6
    problems = problem_generator(prob_num, difficulty=difficulty)
    show_problems_in_columns(problems)

In [49]:
M = np.random.randint(size = (13,11), low = -5, high = 5)

def arb_format_coef(prevcoef, coef, var):

    #Properly formats system of equations depending on coefficient

    if var == 'x_1':
        if coef == 0:
            return "&"
        elif coef == 1:
            return f'&{var}'
        elif coef == -1:
            return f"-&{var}"
        else:
            return f"{coef}&{var}"

    if coef == 0:
        return ""
    elif coef == 1 and prevcoef == 0 and var == 'x_2':
        return f"{var}"
    elif coef == 1:
        return f"+{var}"
    elif coef == -1:
        return f"-{var}"
    elif coef > 0:
        return f"+{coef}{var}"
    else:
        return f"{coef}{var}"

def arb_matrix_to_tex(matrix):

    # Builds LaTeX string

    equations, variables = matrix.shape

    latex_str = r"\begin{cases}"
    latex_str += r"\begin{aligned}"
    for i in range(equations):
        latex_str += f"{arb_format_coef(1, matrix[i][0],'x_1')}"
        for j in range(1, variables-1):
            latex_str += f"{arb_format_coef(matrix[i][j-1], matrix[i][j],f'x_{{{j+1}}}')}"
        latex_str += f"= {matrix[i][-1]} \\\\"
    latex_str += r"\end{aligned}"
    latex_str += r"\end{cases}"

    return latex_str

latex = arb_matrix_to_tex(M)

print(M)

print(latex)

[[ 3 -2 -3 -4 -3 -3  3 -4 -5  3 -1]
 [-3 -3 -5  2 -5 -2  2 -1 -2 -5 -4]
 [ 0 -3  1 -1 -5  3 -1  0 -4  3 -2]
 [-4  1  0 -1  4 -5  4  1 -4  4  4]
 [ 0 -3 -3  4 -5 -1 -1  3  0  4 -1]
 [-4  3  0  1  1 -1 -2  2  4 -3 -3]
 [ 4 -4 -5 -1 -5 -3  4  2 -3 -1  2]
 [ 0  3 -1  0  4 -3 -3 -3  0  3  0]
 [ 3 -1  1  1 -2  1 -5  4 -4  2  3]
 [ 1  3  3 -3 -4  0  0 -2  1  0 -1]
 [-4  0  1 -1  3 -2 -5 -4 -4  1 -1]
 [ 4  1 -4 -4 -2 -4  0  2 -1 -2 -1]
 [-5  2 -5  2  3 -5  3 -1 -3 -2  1]]
\begin{cases}\begin{aligned}3&x_1-2x_{2}-3x_{3}-4x_{4}-3x_{5}-3x_{6}+3x_{7}-4x_{8}-5x_{9}+3x_{10}= -1 \\-3&x_1-3x_{2}-5x_{3}+2x_{4}-5x_{5}-2x_{6}+2x_{7}-x_{8}-2x_{9}-5x_{10}= -4 \\&-3x_{2}+x_{3}-x_{4}-5x_{5}+3x_{6}-x_{7}-4x_{9}+3x_{10}= -2 \\-4&x_1+x_{2}-x_{4}+4x_{5}-5x_{6}+4x_{7}+x_{8}-4x_{9}+4x_{10}= 4 \\&-3x_{2}-3x_{3}+4x_{4}-5x_{5}-x_{6}-x_{7}+3x_{8}+4x_{10}= -1 \\-4&x_1+3x_{2}+x_{4}+x_{5}-x_{6}-2x_{7}+2x_{8}+4x_{9}-3x_{10}= -3 \\4&x_1-4x_{2}-5x_{3}-x_{4}-5x_{5}-3x_{6}+4x_{7}+2x_{8}-3x_{9}-x_{10}= 2 \\&+3x_{2}-x_{3}+4x_{5

In [46]:
eqn, var = M.shape

for i in range(1,var):
    print(f'{i}')


1
2
3
4
5
6
7
8
9
10


In [50]:
def format_coef3x4(prevcoef1,prevcoef2, coef, var):

    #Properly formats system of equations depending on coefficient

    if var == 'x':
        if coef == 0:
            return "&"
        elif coef == 1:
            return f'&{var}'
        elif coef == -1:
            return f"-&{var}"
        else:
            return f"{coef}&{var}"

    if coef == 0:
        return ""
    elif coef == 1 and prevcoef1 == 0 and prevcoef2 == 0:
        return f"{var}"
    elif coef == 1:
        return f"+{var}"
    elif coef == -1:
        return f"-{var}"
    elif coef > 0 and (prevcoef1 != 0 or prevcoef2 != 0):
        return f"+{coef}{var}"
    else:
        return f"{coef}{var}"

def matrix_to_tex3x4(matrix):
    """
    Converts a 3x4 augmented matrix into a LaTeX system of equations
    with variables x, y, z.
    """

    # Unpack rows
    a, b, c, d = matrix[0]
    e, f, g, h = matrix[1]
    i, j, k, l = matrix[2]

    latex_str = r"\begin{cases}"
    latex_str += r"\begin{aligned}"

    # Row 1
    latex_str += (
        f"{format_coef3x4(0, 0, a, 'x')}"
        f"{format_coef3x4(a, 0, b, 'y')}"
        f"{format_coef3x4(a, b, c, 'z')}"
        f"= {d} \\\\"
    )

    # Row 2
    latex_str += (
        f"{format_coef3x4(0, 0, e, 'x')}"
        f"{format_coef3x4(e, 0, f, 'y')}"
        f"{format_coef3x4(e, f, g, 'z')}"
        f"= {h} \\\\"
    )

    # Row 3
    latex_str += (
        f"{format_coef3x4(0, 0, i, 'x')}"
        f"{format_coef3x4(i, 0, j, 'y')}"
        f"{format_coef3x4(i, j, k, 'z')}"
        f"= {l}"
    )

    latex_str += r"\end{aligned}"
    latex_str += r"\end{cases}"

    return latex_str

In [53]:
matrix = np.random.randint(size=(3,4), low = -5, high = 5)

latex = matrix_to_tex3x4(matrix)

print(latex)

\begin{cases}\begin{aligned}-2&x-y-3z= -2 \\3&x+3y+2z= -5 \\-2&x+4y= 0\end{aligned}\end{cases}
